import { notFound } from "next/navigation";
import { Suspense } from "react";
import { PrintGenerator } from "./print-generator";

const KINDS: Record<string, { title: string; eyebrow: string }> = {
  devotional: { title: "Personal Devotional", eyebrow: "Generated by AskScripture" },
  family: { title: "Family Devotional", eyebrow: "Generated by AskScripture" },
  sermon: { title: "Sermon Outline", eyebrow: "Generated by AskScripture" },
  story: { title: "Story", eyebrow: "Story mode · AskScripture" },
};

type Params = { kind: string };
type Search = { ref?: string };

export default function PrintPage({
  params,
  searchParams,
}: {
  params: Promise<Params>;
  searchParams: Promise<Search>;
}) {
  return (
    <Suspense fallback={<PrintSkeleton />}>
      <Content params={params} searchParams={searchParams} />
    </Suspense>
  );
}

async function Content({
  params,
  searchParams,
}: {
  params: Promise<Params>;
  searchParams: Promise<Search>;
}) {
  const [{ kind }, sp] = await Promise.all([params, searchParams]);
  const k = KINDS[kind];
  if (!k) notFound();

  return (
    <div className="doc">
      <div className="controls">
        <span>This page is print-styled. Use your browser's <strong>Print → Save as PDF</strong>.</span>
        <PrintButton />
      </div>
      <div className="eyebrow">{k.eyebrow}</div>
      <h1>{k.title}{sp.ref ? <span style={{ color: "#5b6271", fontWeight: 400 }}> · {sp.ref}</span> : null}</h1>
      <PrintGenerator kind={kind} initialRef={sp.ref ?? ""} />
      <div className="meta">
        Generated by AskScripture · askscripture.com<br />
        Treat AI-assisted content as a study partner, not authority.
      </div>
    </div>
  );
}

function PrintButton() {
  return null;
}

/** Print-styled skeleton — uses the inline `doc` class from print/layout.tsx */
function PrintSkeleton() {
  return (
    <div className="doc">
      <div className="eyebrow">Loading</div>
      <h1 style={{ color: "#d6cfbd" }}>Loading…</h1>
      <div
        style={{
          background: "#f5f2ea",
          height: 16,
          width: "82%",
          margin: "16px 0",
        }}
      />
      <div
        style={{ background: "#f5f2ea", height: 16, width: "94%", margin: "8px 0" }}
      />
      <div
        style={{ background: "#f5f2ea", height: 16, width: "78%", margin: "8px 0" }}
      />
      <div
        style={{ background: "#f5f2ea", height: 16, width: "88%", margin: "8px 0" }}
      />
    </div>
  );
}
